### PR TITLE
Change course and library keys to use OpenedX, DemoCourse, etc

### PR DESCRIPTION
**Pull request by kdmccormick**
Per convo in https://github.com/openedx/openedx-demo-course/pull/49#discussion_r1482010873

**Before**
* course-v1:Axim+DemoX+demo_course
* library-v1:Dummy+RESP_Q1

**After**
* course-v1:OpenedX+DemoX+DemoCourse
* library-v1:OpenedX+DemoRespiratoryQuestions

### CODE REVIEW

**Review by sarina — APPROVED** [review]
LooksgooD
OncetheorG
IschangedtO
OpenedX

**Comment by kdmccormick** [comment]
image

**Comment by kdmccormick** [comment]
@sarina With us using OpenedX now, it was driving me crazy that everything besides demo_course was camel case, so I've pushed one last commit that changes the run from `demo_course` to `DemoCourse`.

So now we have:

**Before**
* course-v1:Axim+DemoX+demo_course
* library-v1:Dummy+RESP_Q1

**After**
* course-v1:OpenedX+DemoX+DemoCourse
* library-v1:OpenedX+DemoRespiratoryQuestions

Any objections?

**Comment by sarina** [comment]
@kdmccormick Overall I appreciate you as an engineer, so much. This attention to detail - and the _need_ to make things right - exemplify this. Thank you for being you. Approved.

**Pull request merged**
